### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ankuPRK** [ewrfcas/MST_inpainting#1]
Hey guys

Thanks for sharing your work and releasing the code. However officially you would need to add a license to allow people to use your code or to build upon it for academic/industrial research.

You can probably add Apache-2.0 License like the mmediting (https://github.com/open-mmlab/mmediting) or BSD License like pix2pixHD (https://github.com/NVIDIA/pix2pixHD) or anything else

Do you plan to add a License to your code?

**Comment by ewrfcas** [comment]
Thanks. I have added the license.
